SELECT NAME,TOTAL_MB,FREE_MB,USABLE_FILE_MB,STATE FROM V$ASM_DISKGROUP;
SELECT NAME,MOUNT_STATUS,TOTAL_MB,FREE_MB,PATH FROM V$ASM_DISK ORDER BY 1;
SELECT NAME,HEADER_STATUS FROM V$ASM_DISK WHERE HEADER_STATUS<>'MEMBER';

ocrcheck
crsctl query css votedisk
ocrconfig -showbackup
