COL DISK_FILE_PATH FOR A35;
SELECT NVL(A.NAME, '[CANDIDATE]') DISK_GROUP_NAME, B.PATH DISK_FILE_PATH, B.NAME DISK_FILE_NAME, B.FAILGROUP DISK_FILE_FAIL_GROUP
FROM V$ASM_DISKGROUP A RIGHT OUTER JOIN V$ASM_DISK B USING (GROUP_NUMBER)
ORDER BY A.NAME;

SELECT NAME, STATE, TYPE, TOTAL_MB, FREE_MB,REQUIRED_MIRROR_FREE_MB ,USABLE_FILE_MB FROM V$ASM_DISKGROUP;

COL PATH FORMAT A45;
COL NAME FORMAT A20;
SELECT NAME, PATH, GROUP_NUMBER, TOTAL_MB, FREE_MB, READS, WRITES, READ_TIME, WRITE_TIME FROM V$ASM_DISK ORDER BY 3,1;

COL PATH FORMAT A50;
COL HEADER_STATUS FORMAT A12;
COL NAME FORMAT A25;
SELECT NAME, PATH, MOUNT_STATUS,HEADER_STATUS, MODE_STATUS, STATE, GROUP_NUMBER, OS_MB, TOTAL_MB, FREE_MB, READS, WRITES, READ_TIME, WRITE_TIME, BYTES_READ,
BYTES_WRITTEN, REPAIR_TIMER, MOUNT_DATE, CREATE_DATE
FROM V$ASM_DISK;
