--Generate script
SET LINES 150 PAGES 5000 TIMING ON;
SELECT
'EXEC DBMS_STATS.GATHER_TABLE_STATS('''||OWNER||''', '''||TABLE_NAME||''', ESTIMATE_PERCENT => 33, CASCADE => TRUE);'
GATH_TABLE FROM DBA_TABLES WHERE OWNER='&SKEMA' ORDER BY 1;

GatherHR.sql
-------------
SPOOL D:\GatherHR.log
SET TIME ON LINES 150 PAGES 5000 TIMING ON ECHO ON;
ALTER SESSION SET NLS_DATE_FORMAT='DD-Mon-RR HH24:MI:SS';
SELECT SYSDATE MULAI FROM DUAL;
EXEC DBMS_STATS.GATHER_TABLE_STATS('HR', 'COUNTRIES', ESTIMATE_PERCENT => 33, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('HR', 'DEPARTMENTS', ESTIMATE_PERCENT => 33, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('HR', 'EMPLOYEES', ESTIMATE_PERCENT => 33, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('HR', 'JOBS', ESTIMATE_PERCENT => 33, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('HR', 'JOB_HISTORY', ESTIMATE_PERCENT => 33, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('HR', 'LOCATIONS', ESTIMATE_PERCENT => 33, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('HR', 'REGIONS', ESTIMATE_PERCENT => 33, CASCADE => TRUE);
SELECT SYSDATE SELESAI FROM DUAL;
COL IDX FOR A35;
COL TBL FOR A35;
SELECT OWNER||'.'||INDEX_NAME IDX,TABLE_OWNER||'.'||TABLE_NAME TBL,LAST_ANALYZED FROM DBA_INDEXES
WHERE TABLE_OWNER='HR' ORDER BY 2,1;
SELECT OWNER||'.'||TABLE_NAME TBL,LAST_ANALYZED FROM DBA_TABLES WHERE OWNER='HR' ORDER BY 1;
SPOOL OFF;
SET TIME OFF;
EXIT;

GatherHR.bat
-------------
D:
dir
set ORACLE_BASE=C:\u01\prastyo
set ORACLE_HOME=C:\u01\prastyo\product\12.1.0.1.0\dbhome_1
set ORACLE_SID=PATTRICK
C:\u01\prastyo\product\12.1.0.1.0\dbhome_1\bin\sqlplus system/orekel789 @D:\GatherHR.sql

--Bikin program
BEGIN
  DBMS_SCHEDULER.create_program
  (
    program_name        => 'PROG_GatherHR',
    program_type        => 'EXECUTABLE',
    program_action      => 'C:\Windows\SysWOW64\cmd.exe /c D:\GatherHR.bat',
    number_of_arguments => 0,
    enabled             => TRUE,
    comments            => 'Program Gather Statistic Table of HR using shell script by AzizPW - MII.'
  );
END;
/

-- Display the program details.
SET LINES 150 PAGES 5000 TIMING ON;
COL OWNER FOR A20;
COL PROGRAM_NAME FOR A35;
COL COMMENTS FOR A80;
SELECT OWNER, PROGRAM_NAME, ENABLED, COMMENTS FROM DBA_SCHEDULER_PROGRAMS ORDER BY 1,2;

--Bikin job
BEGIN
  -- Job defined by an existing program and schedule.
  DBMS_SCHEDULER.create_job
  (
    job_name      	=> 'JOB_GatherHR',
    program_name 	=> 'PROG_GatherHR',
    start_date		=> SYSTIMESTAMP,
    repeat_interval	=> 'freq=weekly; byday=tue; byhour=14; byminute=28; bysecond=00;',
    end_date        => NULL,
    enabled       	=> TRUE,
    comments      	=> 'Job Gather Statistic Table of HR using shell script by AzizPW - MII.'
  );
END;
/

-- Display the job details.
SET LINES 150 PAGES 5000 TIMING ON;
COL JOB_NAME FOR A35;
COL REPEAT_INTERVAL FOR A40;
COL JOB_ACTION FOR A20;
COL COMMENTS FOR A80;
COL STATE FOR A9;
SELECT OWNER||'.'||JOB_NAME JOB_NAME,STATE,REPEAT_INTERVAL,ENABLED,JOB_ACTION,COMMENTS
FROM DBA_SCHEDULER_JOBS WHERE UPPER(JOB_NAME) LIKE '%GATHER%' ORDER BY 1;

-- Display job run detail
SET LINES 150 PAGES 5000 TIMING ON ECHO ON;
COL JOBNAME FOR A30;
COL STATUS FOR A9;
COL ACTUAL_START_DATE FOR A35;
COL RUN_DURATION FOR A15;
COL ADDITIONAL_INFO FOR A80;
SELECT OWNER||'.'||JOB_NAME JOBNAME, STATUS, ERROR#, ACTUAL_START_DATE, RUN_DURATION, ADDITIONAL_INFO
FROM DBA_SCHEDULER_JOB_RUN_DETAILS WHERE UPPER(JOB_NAME) LIKE '%GATHER%' ORDER BY ACTUAL_START_DATE DESC;

--Drop job
BEGIN
  DBMS_SCHEDULER.drop_job (job_name => 'SYS.JOB_GATHERSCOTT');
END;
/

--Drop program
BEGIN
  DBMS_SCHEDULER.drop_program (program_name => 'SYS.PROG_GATHERSCOTT');
  DBMS_SCHEDULER.drop_program (program_name => 'SYS.PROG_GATHERHR');
END;
/
