--Jadikan archivelog mode
[orekel@rhino ~]$ mkdir -p /z02/arc/badak

SQL> STARTUP MOUNT;
ORACLE instance started.

Total System Global Area 1610612736 bytes
Fixed Size                  8621232 bytes
Variable Size            1040188240 bytes
Database Buffers          553648128 bytes
Redo Buffers                8155136 bytes
Database mounted.
SQL> ALTER SYSTEM SET log_archive_dest_1='location=/z02/arc/badak' SCOPE=BOTH;

System altered.

Elapsed: 00:00:01.51
SQL> ALTER DATABASE ARCHIVELOG;

Database altered.

Elapsed: 00:00:01.76
SQL> SHO PARAMETER log_archive_dest_1

NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
log_archive_dest_1                   string      location=/z02/arc/badak
log_archive_dest_10                  string
log_archive_dest_11                  string
log_archive_dest_12                  string
log_archive_dest_13                  string
log_archive_dest_14                  string
log_archive_dest_15                  string
log_archive_dest_16                  string
log_archive_dest_17                  string
log_archive_dest_18                  string
log_archive_dest_19                  string
SQL> ALTER SYSTEM SET log_archive_format='%t_%s_%r.arc' SCOPE=SPFILE;

System altered.

Elapsed: 00:00:00.00
SQL> SHO PARAMETER log_archive_format;

NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
log_archive_format                   string      %t_%s_%r.dbf
SQL> SHU IMMEDIATE;
ORA-01109: database not open


Database dismounted.
ORACLE instance shut down.
SQL> STARTUP;
ORACLE instance started.

Total System Global Area 1610612736 bytes
Fixed Size                  8621232 bytes
Variable Size            1040188240 bytes
Database Buffers          553648128 bytes
Redo Buffers                8155136 bytes
Database mounted.
Database opened.
SQL> ARCHIVE LOG LIST;
Database log mode              Archive Mode
Automatic archival             Enabled
Archive destination            /z02/arc/badak
Oldest online log sequence     1
Next log sequence to archive   2
Current log sequence           2
SQL>

--Force logging
SQL> ALTER DATABASE FORCE LOGGING;

Database altered.

Elapsed: 00:00:00.05
SQL>

--Create standy logfile
SQL> ALTER DATABASE ADD STANDBY LOGFILE ('/z01/onlinelog/badak/standby_redo01.log') SIZE 200M;

Database altered.

Elapsed: 00:00:04.15
SQL> ALTER DATABASE ADD STANDBY LOGFILE ('/z01/onlinelog/badak/standby_redo02.log') SIZE 200M;

Database altered.

Elapsed: 00:00:04.97
SQL> ALTER DATABASE ADD STANDBY LOGFILE ('/z01/onlinelog/badak/standby_redo03.log') SIZE 200M;

Database altered.

Elapsed: 00:00:04.00
SQL> ALTER DATABASE ADD STANDBY LOGFILE ('/z01/onlinelog/badak/standby_redo04.log') SIZE 200M;

Database altered.

Elapsed: 00:00:04.50
SQL>

--Enable flashback
SQL> ALTER SYSTEM SET db_recovery_file_dest_size=5g;

System altered.

Elapsed: 00:00:00.35
SQL> ALTER SYSTEM SET db_recovery_file_dest='/z02/arc/badak';

System altered.

Elapsed: 00:00:00.07
SQL> ALTER DATABASE FLASHBACK ON;

Database altered.

Elapsed: 00:00:06.07
SQL>

--Edit tnsnames.ora
[orekel@rhino ~]$ cp $ORACLE_HOME/network/admin/tnsnames.ora $ORACLE_HOME/network/admin/tnsnames_ori_20170430.ora
[orekel@rhino ~]$ nano $ORACLE_HOME/network/admin/tnsnames.ora
[orekel@rhino ~]$ cat $ORACLE_HOME/network/admin/tnsnames.ora
# tnsnames.ora Network Configuration File: /z02/app/orekel/product/12.2.0.1/db_1/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

BADAK =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = rhino.animal.net)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = BADAK)
    )
  )

KUDANIL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = hippo.animal.net)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = KUDANIL)
    )
  )
[orekel@rhino ~]$ scp $ORACLE_HOME/network/admin/tnsnames.ora orekel@hippo.animal.net:/z02/app/orekel/product/12.2.0.1/db_1/network/admin
orekel@hippo.animal.net''s password:
tnsnames.ora                                                                                                                     100%  503     0.5KB/s   00:00
[orekel@rhino ~]$

--Edit listener.ora
[orekel@rhino ~]$ nano $ORACLE_HOME/network/admin/listener.ora
[orekel@rhino ~]$ cat $ORACLE_HOME/network/admin/listener.ora
# listener.ora Network Configuration File: /z02/app/orekel/product/12.2.0.1/db_1/network/admin/listener.ora
# Generated by Oracle configuration tools.

LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = rhino.animal.net)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = BADAK_DGMGRL)
      (ORACLE_HOME = /z02/app/orekel/product/12.2.0.1/db_1)
      (SID_NAME = BADAK)
    )
  )

ADR_BASE_LISTENER = /z02/app/orekel
[orekel@rhino ~]$

[orekel@hippo ~]$ nano $ORACLE_HOME/network/admin/listener.ora
[orekel@hippo ~]$ cat $ORACLE_HOME/network/admin/listener.ora
# listener.ora Network Configuration File: /z02/app/orekel/product/12.2.0.1/db_1/network/admin/listener.ora
# Generated by Oracle configuration tools.

LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = hippo.animal.net)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (GLOBAL_DBNAME = KUDANIL_DGMGRL)
      (ORACLE_HOME = /z02/app/orekel/product/12.2.0.1/db_1)
      (SID_NAME = KUDANIL)
    )
  )

ADR_BASE_LISTENER = /z02/app/orekel
[orekel@hippo ~]$

--Restart listener
[orekel@rhino ~]$ lsnrctl stop LISTENER; lsnrctl start LISTENER;

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 30-APR-2017 20:46:15

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=rhino.animal.net)(PORT=1521)))
The command completed successfully

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 30-APR-2017 20:46:15

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /z02/app/orekel/product/12.2.0.1/db_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /z02/app/orekel/product/12.2.0.1/db_1/network/admin/listener.ora
Log messages written to /z02/app/orekel/diag/tnslsnr/rhino/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=rhino.animal.net)(PORT=1521)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=rhino.animal.net)(PORT=1521)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                30-APR-2017 20:46:15
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /z02/app/orekel/product/12.2.0.1/db_1/network/admin/listener.ora
Listener Log File         /z02/app/orekel/diag/tnslsnr/rhino/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=rhino.animal.net)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))
Services Summary...
Service "BADAK_DGMGRL" has 1 instance(s).
  Instance "BADAK", status UNKNOWN, has 1 handler(s) for this service...
The command completed successfully
[orekel@rhino ~]$

[orekel@hippo ~]$ lsnrctl stop LISTENER; lsnrctl start LISTENER;

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 30-APR-2017 20:47:00

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hippo.animal.net)(PORT=1521)))
TNS-12541: TNS:no listener
 TNS-12560: TNS:protocol adapter error
  TNS-00511: No listener
   Linux Error: 111: Connection refused
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1521)))
TNS-12541: TNS:no listener
 TNS-12560: TNS:protocol adapter error
  TNS-00511: No listener
   Linux Error: 111: Connection refused

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 30-APR-2017 20:47:02

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /z02/app/orekel/product/12.2.0.1/db_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /z02/app/orekel/product/12.2.0.1/db_1/network/admin/listener.ora
Log messages written to /z02/app/orekel/diag/tnslsnr/hippo/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=hippo.animal.net)(PORT=1521)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hippo.animal.net)(PORT=1521)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                30-APR-2017 20:47:04
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /z02/app/orekel/product/12.2.0.1/db_1/network/admin/listener.ora
Listener Log File         /z02/app/orekel/diag/tnslsnr/hippo/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=hippo.animal.net)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))
Services Summary...
Service "KUDANIL_DGMGRL" has 1 instance(s).
  Instance "KUDANIL", status UNKNOWN, has 1 handler(s) for this service...
The command completed successfully
[orekel@hippo ~]$

--Copy pfile to standby
SQL> create pfile='/home/orekel/initBADAK_20170430.ora' from spfile;

File created.

Elapsed: 00:00:00.05
SQL> exit
Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
[orekel@rhino ~]$ scp /home/orekel/initBADAK_20170430.ora orekel@hippo:/home/orekel/initKUDANIL_20170430.ora
orekel@hippo''s password:
initBADAK_20170430.ora                                                                                                           100% 1573     1.5KB/s   00:00
[orekel@rhino ~]$

--Copy controlfile
SQL> ALTER DATABASE CREATE STANDBY CONTROLFILE AS '/home/orekel/badak_stby.ctl';

Database altered.

Elapsed: 00:00:00.32
SQL> exit
Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
[orekel@rhino ~]$ scp /home/orekel/badak_stby.ctl orekel@hippo:/z01/controlfile/badak/control01.ctl
orekel@hippo''s password:
badak_stby.ctl                                                                                                                   100%   10MB  10.1MB/s   00:01
[orekel@rhino ~]$ scp /home/orekel/badak_stby.ctl orekel@hippo:/z01/controlfile/badak/control02.ctl
orekel@hippo''s password:
badak_stby.ctl                                                                                                                   100%   10MB  10.1MB/s   00:01
[orekel@rhino ~]$

--Edit pfile standby and create spfile
[orekel@hippo ~]$ nano initKUDANIL_20170430.ora
[orekel@hippo ~]$ cat initKUDANIL_20170430.ora
KUDANIL.__data_transfer_cache_size=0
KUDANIL.__db_cache_size=419430400
KUDANIL.__inmemory_ext_roarea=0
KUDANIL.__inmemory_ext_rwarea=0
KUDANIL.__java_pool_size=16777216
KUDANIL.__large_pool_size=33554432
KUDANIL.__oracle_base='/z02/app/orekel'#ORACLE_BASE set from environment
KUDANIL.__pga_aggregate_target=872415232
KUDANIL.__sga_target=738197504
KUDANIL.__shared_io_pool_size=33554432
KUDANIL.__shared_pool_size=218103808
KUDANIL.__streams_pool_size=0
*.audit_file_dest='/z02/app/orekel/admin/badak/adump'
*.audit_trail='db'
*.compatible='12.2.0'
*.control_files='/z01/controlfile/badak/control01.ctl','/z01/controlfile/badak/control02.ctl'
*.db_block_size=8192
*.db_domain='animal.net'
*.db_name='badak'
*.db_recovery_file_dest_size=5368709120
*.db_recovery_file_dest='/z02/arc/badak'
*.db_unique_name='KUDANIL'
*.diagnostic_dest='/z02/app/orekel'
*.fal_client='KUDANIL'
*.fal_server='BADAK'
*.log_archive_config='DG_CONFIG=(BADAK,KUDANIL)'
*.log_archive_dest_1='location=/z02/arc/badak valid_for=(all_logfiles,all_roles) db_unique_name=KUDANIL'
*.log_archive_dest_2='SERVICE=BADAK NOAFFIRM ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=BADAK'
*.log_archive_dest_state_2='DEFER'
*.log_archive_format='%t_%s_%r.arc'
*.log_archive_max_processes=30
*.memory_max_target=1610612736
*.memory_target=1610612736
*.nls_language='AMERICAN'
*.nls_territory='AMERICA'
*.open_cursors=300
*.processes=300
*.remote_login_passwordfile='EXCLUSIVE'
*.standby_file_management='AUTO'
*.undo_tablespace='UNDOTBS1'
[orekel@hippo ~]$ rlwrap sqlplus sys/orekel789 as sysdba

SQL*Plus: Release 12.2.0.1.0 Production on Sun Apr 30 20:57:05 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> CREATE SPFILE FROM PFILE='/home/orekel/initKUDANIL_20170430.ora';

File created.

Elapsed: 00:00:00.35
SQL> STARTUP NOMOUNT;

Message from syslogd@hippo at Apr 30 21:00:29 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [khugepaged:31]
ORACLE instance started.

Total System Global Area 1610612736 bytes
Fixed Size                  8621232 bytes
Variable Size            1140851536 bytes
Database Buffers          452984832 bytes
Redo Buffers                8155136 bytes
SQL>

--Duplicate database to primary
[orekel@rhino ~]$ rlwrap rman target sys/orekel789@BADAK AUXILIARY sys/orekel789@KUDANIL

Recovery Manager: Release 12.2.0.1.0 - Production on Sun Apr 30 21:03:46 2017

Copyright (c) 1982, 2017, Oracle and/or its affiliates.  All rights reserved.

connected to target database: BADAK (DBID=4004843522)
connected to auxiliary database: BADAK (not mounted)

RMAN> DUPLICATE TARGET DATABASE FOR STANDBY FROM ACTIVE DATABASE DORECOVER NOFILENAMECHECK;

Starting Duplicate Db at 30-Apr-17 21:06:41
using target database control file instead of recovery catalog
allocated channel: ORA_AUX_DISK_1
channel ORA_AUX_DISK_1: SID=20 device type=DISK
current log archived

contents of Memory Script:
{
   backup as copy reuse
   targetfile  '/z02/app/orekel/product/12.2.0.1/db_1/dbs/orapwBADAK' auxiliary format
 '/z02/app/orekel/product/12.2.0.1/db_1/dbs/orapwKUDANIL'   ;
}
executing Memory Script

Starting backup at 30-Apr-17 21:06:59
allocated channel: ORA_DISK_1
channel ORA_DISK_1: SID=288 device type=DISK
Finished backup at 30-Apr-17 21:07:06

contents of Memory Script:
{
   restore clone from service  'BADAK' standby controlfile;
}
executing Memory Script

Starting restore at 30-Apr-17 21:07:06
using channel ORA_AUX_DISK_1

channel ORA_AUX_DISK_1: starting datafile backup set restore
channel ORA_AUX_DISK_1: using network backup set from service BADAK
channel ORA_AUX_DISK_1: restoring control file
channel ORA_AUX_DISK_1: restore complete, elapsed time: 00:00:05
output file name=/z01/controlfile/badak/control01.ctl
output file name=/z01/controlfile/badak/control02.ctl
Finished restore at 30-Apr-17 21:07:12

contents of Memory Script:
{
   sql clone 'alter database mount standby database';
}
executing Memory Script

sql statement: alter database mount standby database

contents of Memory Script:
{
   set newname for tempfile  1 to
 "/z01/datafile/badak/temp01.dbf";
   switch clone tempfile all;
   set newname for datafile  1 to
 "/z01/datafile/badak/system01.dbf";
   set newname for datafile  3 to
 "/z01/datafile/badak/sysaux01.dbf";
   set newname for datafile  4 to
 "/z01/datafile/badak/undotbs01.dbf";
   set newname for datafile  7 to
 "/z01/datafile/badak/users01.dbf";
   restore
   from  nonsparse   from service
 'BADAK'   clone database
   ;
   sql 'alter system archive log current';
}
executing Memory Script

executing command: SET NEWNAME

renamed tempfile 1 to /z01/datafile/badak/temp01.dbf in control file

executing command: SET NEWNAME

executing command: SET NEWNAME

executing command: SET NEWNAME

executing command: SET NEWNAME

Starting restore at 30-Apr-17 21:07:20
using channel ORA_AUX_DISK_1

channel ORA_AUX_DISK_1: starting datafile backup set restore
channel ORA_AUX_DISK_1: using network backup set from service BADAK
channel ORA_AUX_DISK_1: specifying datafile(s) to restore from backup set
channel ORA_AUX_DISK_1: restoring datafile 00001 to /z01/datafile/badak/system01.dbf
channel ORA_AUX_DISK_1: restore complete, elapsed time: 00:05:16
channel ORA_AUX_DISK_1: starting datafile backup set restore
channel ORA_AUX_DISK_1: using network backup set from service BADAK
channel ORA_AUX_DISK_1: specifying datafile(s) to restore from backup set
channel ORA_AUX_DISK_1: restoring datafile 00003 to /z01/datafile/badak/sysaux01.dbf
channel ORA_AUX_DISK_1: restore complete, elapsed time: 00:01:11
channel ORA_AUX_DISK_1: starting datafile backup set restore
channel ORA_AUX_DISK_1: using network backup set from service BADAK
channel ORA_AUX_DISK_1: specifying datafile(s) to restore from backup set
channel ORA_AUX_DISK_1: restoring datafile 00004 to /z01/datafile/badak/undotbs01.dbf
channel ORA_AUX_DISK_1: restore complete, elapsed time: 00:00:09
channel ORA_AUX_DISK_1: starting datafile backup set restore
channel ORA_AUX_DISK_1: using network backup set from service BADAK
channel ORA_AUX_DISK_1: specifying datafile(s) to restore from backup set
channel ORA_AUX_DISK_1: restoring datafile 00007 to /z01/datafile/badak/users01.dbf
channel ORA_AUX_DISK_1: restore complete, elapsed time: 00:00:01
Finished restore at 30-Apr-17 21:14:00

sql statement: alter system archive log current
current log archived

contents of Memory Script:
{
   restore clone force from service  'BADAK'
           archivelog from scn  1722712;
   switch clone datafile all;
}
executing Memory Script

Starting restore at 30-Apr-17 21:14:02
using channel ORA_AUX_DISK_1

channel ORA_AUX_DISK_1: starting archived log restore to default destination
channel ORA_AUX_DISK_1: using network backup set from service BADAK
channel ORA_AUX_DISK_1: restoring archived log
archived log thread=1 sequence=14
channel ORA_AUX_DISK_1: restore complete, elapsed time: 00:00:01
channel ORA_AUX_DISK_1: starting archived log restore to default destination
channel ORA_AUX_DISK_1: using network backup set from service BADAK
channel ORA_AUX_DISK_1: restoring archived log
archived log thread=1 sequence=15
channel ORA_AUX_DISK_1: restore complete, elapsed time: 00:00:01
Finished restore at 30-Apr-17 21:14:05

datafile 1 switched to datafile copy
input datafile copy RECID=3 STAMP=942700446 file name=/z01/datafile/badak/system01.dbf
datafile 3 switched to datafile copy
input datafile copy RECID=4 STAMP=942700446 file name=/z01/datafile/badak/sysaux01.dbf
datafile 4 switched to datafile copy
input datafile copy RECID=5 STAMP=942700446 file name=/z01/datafile/badak/undotbs01.dbf
datafile 7 switched to datafile copy
input datafile copy RECID=6 STAMP=942700446 file name=/z01/datafile/badak/users01.dbf

contents of Memory Script:
{
   set until scn  1723658;
   recover
   standby
   clone database
    delete archivelog
   ;
}
executing Memory Script

executing command: SET until clause

Starting recover at 30-Apr-17 21:14:06
using channel ORA_AUX_DISK_1

starting media recovery

archived log for thread 1 with sequence 14 is already on disk as file /z02/arc/badak/1_14_942166852.arc
archived log for thread 1 with sequence 15 is already on disk as file /z02/arc/badak/1_15_942166852.arc
archived log file name=/z02/arc/badak/1_14_942166852.arc thread=1 sequence=14
archived log file name=/z02/arc/badak/1_15_942166852.arc thread=1 sequence=15
media recovery complete, elapsed time: 00:00:01
Finished recover at 30-Apr-17 21:14:12
Finished Duplicate Db at 30-Apr-17 21:14:47

RMAN>

--Setting Parameter ODG, look at the pfile and start MRP on standby
SQL> RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;
Media recovery complete.
SQL>

--Enable broker parameter
SQL> ALTER SYSTEM SET dg_broker_start=TRUE;

System altered.

Elapsed: 00:00:02.42
SQL> !hostname
rhino.animal.net

SQL>

SQL> ALTER SYSTEM SET dg_broker_start=TRUE;

System altered.

Elapsed: 00:00:02.78
SQL> !hostname
hippo.animal.net

SQL>

--Config Broker
[orekel@rhino ~]$ rlwrap dgmgrl sys/orekel789
DGMGRL for Linux: Release 12.2.0.1.0 - Production on Sun Apr 30 21:20:18 2017

Copyright (c) 1982, 2017, Oracle and/or its affiliates.  All rights reserved.

Welcome to DGMGRL, type "help" for information.
Connected to "BADAK"
Connected as SYSDBA.
DGMGRL> CREATE CONFIGURATION 'Animal' AS PRIMARY DATABASE IS 'BADAK' CONNECT IDENTIFIER IS 'BADAK';
Configuration "Animal" created with primary database "BADAK"
DGMGRL>