--THIS SCRIPT IS USED TO CHECK STANDBY SYNC STATUS

SELECT NAME,OPEN_MODE,DATABASE_ROLE FROM V$DATABASE;
SET LINES 200;
COL DEST_NAME FOR A50;
COL BINDING FOR A10;
SELECT PROCESS,STATUS,GROUP#,THREAD#,SEQUENCE#,BLOCK#,DELAY_MINS FROM V$MANAGED_STANDBY;
ARCHIVE LOG LIST;
SELECT COUNT(*)GAP FROM V$ARCHIVE_GAP;
SELECT MAX(SEQUENCE#)MAX_SEQ FROM V$LOG_HISTORY;
COL MESSAGE FOR A150;
SELECT * FROM(SELECT MESSAGE FROM V$DATAGUARD_STATUS WHERE MESSAGE LIKE '%MEDIA RECOVERY LOG%' ORDER BY MESSAGE DESC) WHERE ROWNUM<=5;
