SET LINES 150 PAGES 1000;
COL STATUS FORMAT A25;
COL HOURS FORMAT 999.99;
COL "SPEED/S" FORMAT A10;
COL TOTAL_SIZE FORMAT A10;
COL SERVICE_NAME FORMAT A50;
COL START_TIME FORMAT A20;
COL END_TIME FORMAT A20;
SELECT /*+PARALLEL(8)*/SESSION_RECID AS RECID, SESSION_STAMP, INPUT_TYPE, STATUS, OUTPUT_BYTES_PER_SEC_DISPLAY AS "SPEED/S", OUTPUT_BYTES_DISPLAY AS TOTAL_SIZE,
TO_CHAR(START_TIME,'MM/DD/YY HH24:MI:SS') START_TIME, TO_CHAR(END_TIME,'MM/DD/YY HH24:MI:SS') END_TIME, ELAPSED_SECONDS/3600 HOURS
FROM V$RMAN_BACKUP_JOB_DETAILS ORDER BY SESSION_KEY;
SELECT SID, STATUS, PROCESS, PROGRAM, SERVICE_NAME FROM V$SESSION WHERE STATUS='ACTIVE' AND UPPER(PROGRAM) LIKE '%RMAN%';

SET LINES 150 PAGES 1000;
COL COMMAND_ID FOR A20;
COL START_TIME FOR A20;
COL TIME_TAKEN_DISPLAY FOR A18;
COL STATUS FORMAT A15;
COL INPUT_TYPE FOR A20;
COL OUTDEVICE FOR A10;
COL INPUTBYTES FOR A10;
COL OUT_BYTES FOR A10;
COL OUT_PERSEC FOR A10;
SELECT
COMMAND_ID, TO_CHAR(START_TIME, 'DD-Mon-RR HH24:MI:SS')START_TIME, TIME_TAKEN_DISPLAY, STATUS, INPUT_TYPE, OUTPUT_DEVICE_TYPE OUTDEVICE, INPUT_BYTES_DISPLAY INPUTBYTES,
OUTPUT_BYTES_DISPLAY OUT_BYTES, OUTPUT_BYTES_PER_SEC_DISPLAY OUT_PERSEC
FROM V$RMAN_BACKUP_JOB_DETAILS
ORDER BY 1 DESC;
