SELECT /*+PARALLEL(AUTO)*/ R.COMMAND_ID, TO_CHAR(R.START_TIME, 'mm/dd/yyyy HH24:MI:SS')START_TIME, R.TIME_TAKEN_DISPLAY, R.INPUT_TYPE, R.STATUS,
R.OUTPUT_DEVICE_TYPE, R.INPUT_BYTES_DISPLAY, R.OUTPUT_BYTES_DISPLAY, R.OUTPUT_BYTES_PER_SEC_DISPLAY FROM (SELECT COMMAND_ID, START_TIME, TIME_TAKEN_DISPLAY,
STATUS, INPUT_TYPE, OUTPUT_DEVICE_TYPE, INPUT_BYTES_DISPLAY, OUTPUT_BYTES_DISPLAY, OUTPUT_BYTES_PER_SEC_DISPLAY
FROM V$RMAN_BACKUP_JOB_DETAILS ORDER BY START_TIME DESC) R ORDER BY 2 DESC;

--WHERE INPUT_TYPE NOT IN ('ARCHIVELOG','DB INCR');

SELECT /*+PARALLEL(AUTO)*/ BS.RECID, BP.PIECE#, BP.COPY#, STATUS, HANDLE, TO_CHAR(BP.START_TIME, 'mm/dd/yyyy HH24:MI:SS')START_TIME, TO_CHAR(BP.COMPLETION_TIME, 'mm/dd/yyyy HH24:MI:SS')COMPLETION_TIME, BP.ELAPSED_SECONDS FROM V$BACKUP_SET BS ,V$BACKUP_PIECE BP WHERE BS.SET_STAMP = BP.SET_STAMP AND BS.SET_COUNT = BP.SET_COUNT AND BP.STATUS IN ('A', 'X') ORDER BY BS.RECID, PIECE#;
