SELECT * FROM DBA_JOBS WHERE LOWER(WHAT) LIKE 'statspack.snap%';

SET LINES 150 PAGES 5000 TIMING ON;
COL LOG_USER FOR A35;
COL INTERVAL FOR A20;
COL WHAT FOR A50;
SELECT JOB,LOG_USER,LAST_DATE,LAST_SEC,NEXT_DATE,NEXT_SEC,BROKEN,INTERVAL,FAILURES,WHAT
FROM DBA_JOBS WHERE LOWER(WHAT) LIKE 'statspack.snap%' OR LOWER(WHAT) LIKE '%perfstat%';


--AUTO JOB STATSPACK
BEGIN 
  SYS.DBMS_JOB.REMOVE(10448);
COMMIT;
END;
/

DECLARE
  X NUMBER;
BEGIN
  SYS.DBMS_JOB.SUBMIT
  ( JOB       => X 
   ,WHAT      => 'statspack.snap;'
   ,NEXT_DATE => TO_DATE('06/06/2016 13:00:00','DD/MM/YYYY HH24:MI:SS')
   ,INTERVAL  => 'SYSDATE+60/1440'
   ,NO_PARSE  => FALSE
   ,INSTANCE  => 1
  );
  SYS.DBMS_OUTPUT.PUT_LINE('JOB NUMBER IS: ' || TO_CHAR(X));
COMMIT;
END;
/

--PROCEDURE DELETE SNAPSHOT
CREATE OR REPLACE PROCEDURE PERFSTAT.DELETE_PERFSTAT as
BEGIN
  DELETE FROM stats$snapshot WHERE snap_time < SYSDATE - 1;
  COMMIT;
END DELETE_PERFSTAT;
/

--AUTO JOB DELETE SNAPSHOT
DECLARE
  X NUMBER;
BEGIN
  SYS.DBMS_JOB.SUBMIT
  ( job       => X 
   ,what      => 'perfstat.delete_perfstat;'
   ,next_date => to_date('07/06/2016 00:00:00','dd/mm/yyyy hh24:mi:ss')
   ,interval  => 'TRUNC(SYSDATE + 1)'
   ,no_parse  => FALSE
   ,instance  => 1
  );
  SYS.DBMS_OUTPUT.PUT_LINE('Job Number is: ' || to_char(x));
COMMIT;
END;
/
